Feature/minusvoid add home page
kougakusai/clubhook pull request #2
Opened 2021-06-28 02:21 UTC by minusvoid

## issueURL
#3

## このPRの対応範囲
Page Titleコンポーネント作成。propsでタイトル名を渡して表示をする。

2021-06-28 12:57 UTC, minusvoid commented
https://github.com/kougakusai/clubhook/issues/3#issue-931155854
issue 紐付

2021-07-05 00:01 UTC, ujimattya requested changes
subtitleについて修正があります。

2021-07-05 00:01 UTC, ujimattya commented on src/components/pagetitle.tsx
> +  subtitle: string;
subtitleはホーム画面しか使わないので、?（多分）をつけて任意にしてください。
）

2021-07-05 00:01 UTC, ujimattya commented on src/components/pagetitle.tsx
> +        {props.title} - {props.subtitle}
subtitleは画面によってないことがあるので、三項演算子を使ったりして場合分けしてください

2021-07-07 12:41 UTC, minusvoid commented on src/components/pagetitle.tsx
> +        {props.title} - {props.subtitle}
考えが足りてなかったです。

2021-07-07 13:03 UTC, minusvoid commented
> subtitleについて修正があります。

596c1e2修正済

2021-07-08 04:26 UTC, ujimattya commented on src/components/pagetitle.tsx
>  const PageTitle = (props: PageTitleProps) => {
React.VFC使ってください。

2021-07-08 04:31 UTC, ujimattya commented
Headerコンポーネントをdevelopにマージしたので、それをmergeしてください。index.tsxはdevelopのものを取り込んでください。（いくつかライブラリを入れているのでyarn installが必要です）

2021-07-11 12:17 UTC, ujimattya approved these changes
問題ありません。

2021-07-11 12:18 UTC, merged